Web design
LoxiasCam/NYT-copyArticle pull request #2
Opened 2021-01-15 04:20 UTC by kensayo

Added footer changes, more style, just a few linters to be fixed, still need to modify README.

2021-01-15 07:05 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @LoxiasCam and @kensayo 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes.
- [ ] Please Fix the linter issues
- [ ] Please add the description in `href` attribute
- [ ] Please align the video in center
- [ ] Update the README file as previous TSE explained
##
- **Note: Please do not merge PR before approving the project**
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-01-15 07:05 UTC, umairarshadbutt commented on index.html
> +            <li><a class="footer-link" href="">Home Page</a></li>
Please add the description in `href` attribute

2021-01-15 07:05 UTC, umairarshadbutt commented on index.html
> +            <li><a class="footer-link" href="">World</a></li>
Please add the description in `href` attribute

2021-01-16 00:04 UTC, voscarmv requested changes
# Impressive work, team. 💻 👀 ✨ 
- Great job applying the necessary changes requested by the previous TSE. Your project is almost complete!

## However, there are some changes required 👀 🧰 🔨 🔧 
- In the bottom section of your page there is a broken image that is supposed to contain the NTY logo. Please fix this: 
![image](https://user-images.githubusercontent.com/2739245/104790064-1cfecb00-575c-11eb-89c3-0381c7231e78.png)

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-01-16 08:48 UTC, ElijahTobs requested changes
# Status: Changes Required :recycle: 

## Hi @kensayo and @LoxiasCam  :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this project can be approved.

## REQUIRED

* [x] The text **SPACE & COSMOS** should be present in your navbar.
* [ ] Add the contents of the `Suggested newsletter section`
* [ ] Your Pull Request message should be a short description or summary of what you've done in that Pull Request, not the changes made after a TSE review.

### Make the requested changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

2021-01-16 22:43 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team  ,  you have done a brilliant job with this project. :clap:
#### You can merge !!!

2021-01-16 22:58 UTC, merged